export const teams = [
{
	"id" : "NZ",
	"name" : "New Zealand",
	"multiplier1" : 10,
	"multiplier2" : 0,
	"multiplier3" : 0,
	"multiplier4" : 0,
	"multiplier5" : 0,
	"multiplier6" : 0,
	"multiplier7" : 0,
	"multiplier8" : 0,
	"multiplier20" : 0,
	"group": "B",
	"rank" : 1,
	"oddsfra" : "5/4",
	"oddsdec" : 1.25,
	"rwcwins" : 3,
	"description" : "The All Blacks are the most successful sporting team across any sport ever. They have won 3 world cups and have been ranked as the number 1 side in the world from Nov 2009 to Aug 2019."
},
{
	"id" : "SA",
	"name" : "South Africa",
	"multiplier1" : 15,
	"multiplier2" : 10,
	"multiplier3" : 0,
	"multiplier4" : 0,
	"multiplier5" : 0,
	"multiplier6" : 0,
	"multiplier7" : 0,
	"multiplier8" : 0,
	"multiplier20" : 0,
	"group": "B",
	"rank" : 2,
	"oddsfra" : "9/2",
	"oddsdec" : 4.5,
	"rwcwins" : 2,
	"description" : "The Springboks won the 2019 Rugby Championship in commanding style, beating the All Blacks, and the Pumas, and recording a record breaking win over the Wallabies."
},
{
	"id" : "ENG",
	"name" : "England",
	"multiplier1" : 20,
	"multiplier2" : 15,
	"multiplier3" : 10,
	"multiplier4" : 0,
	"multiplier5" : 0,
	"multiplier6" : 0,
	"multiplier7" : 0,
	"multiplier8" : 0,
	"multiplier20" : 0,
	"group": "C",
	"rank" : 3,
	"oddsfra" : "11/2",
	"oddsdec" : 5.5,
	"rwcwins" : 1,
	"description" : "England went out of their own 2015 World Cup in the group stages, but have world-class players and are lead by mastermind coach Eddie Jones."
},
{ 		
	"id" : "IRE",
	"name" : "Ireland",
	"multiplier1" : 25,
	"multiplier2" : 20,
	"multiplier3" : 15,
	"multiplier4" : 10,
	"multiplier5" : 0,
	"multiplier6" : 0,
	"multiplier7" : 0,
	"multiplier8" : 0,
	"multiplier20" : 0,
	"group": "A",
	"rank" : 4,
	"oddsfra" : "8/1",
	"oddsdec" : 8,
	"rwcwins" : 0,
	"description" : "Ireland have defeated the All Blacks twice in recent years, and have climbed to 2nd in the world ranking in the past year under the stewardship of coach Joe Schmidt."
},
{ 		
	"id" : "WAL",
	"name" : "Wales",
	"multiplier1" : 35,
	"multiplier2" : 30,
	"multiplier3" : 25,
	"multiplier4" : 20,
	"multiplier5" : 10,
	"multiplier6" : 0,
	"multiplier7" : 0,
	"multiplier8" : 0,
	"multiplier20" : 0,
	"group": "D",
	"rank" : 5,
	"oddsfra" : "8/1",
	"oddsdec" : 8,
	"rwcwins" : 0,
	"description" : "Wales are currently ranked the number 1 side in the world, having risen rapidly in the last year. Captain Alun Wyn Jones could be the one to take them all the way..."
},
{ 		
	"id" : "AUS",
	"name" : "Australia",
	"multiplier1" : 35,
	"multiplier2" : 30,
	"multiplier3" : 25,
	"multiplier4" : 20,
	"multiplier5" : 15,
	"multiplier6" : 10,
	"multiplier7" : 0,
	"multiplier8" : 0,
	"multiplier20" : 0,
	"group": "D",
	"rank" : 6,
	"oddsfra" : "12/1",
	"oddsdec" : 12,
	"rwcwins" : 2,
	"description" : "Previous world cup winners, the Wallabies can never truly been written off. Finalists last year, and having defeated the All Blacks this month, it could be theirs again this year."
},
{ 		
	"id" : "FRA",
	"name" : "France",
	"multiplier1" : 35,
	"multiplier2" : 30,
	"multiplier3" : 25,
	"multiplier4" : 20,
	"multiplier5" : 15,
	"multiplier6" : 12,
	"multiplier7" : 10,
	"multiplier8" : 0,
	"multiplier20" : 0,
	"group": "C",
	"rank" : 7,
	"oddsfra" : "33/1",
	"oddsdec" : 33,
	"rwcwins" : 0,
	"description" : "Finalists in 2011, France are an unpredictable team with one of the most well funded and attended domestic leagues in the world."
},
{ 		
	"id" : "ARG",
	"name" : "Argentina",
	"multiplier1" : 35,
	"multiplier2" : 30,
	"multiplier3" : 25,
	"multiplier4" : 20,
	"multiplier5" : 18,
	"multiplier6" : 15,
	"multiplier7" : 12,
	"multiplier8" : 10,
	"multiplier20" : 0,
	"group": "C",
	"rank" : 8,
	"oddsfra" : "40/1",
	"oddsdec" : 40,
	"rwcwins" : 0,
	"description" : "The Pumas compete in the Rugby Championship each year, and continue to improve year-on-year. They also tend to perform strongly at World Cups."
},
{ 		
	"id" : "SCO",
	"name" : "Scotland",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "A",
	"rank" : 9,
	"oddsfra" : "50/1",
	"oddsdec" : 50,
	"rwcwins" : 0,
	"description" : "Scotland are never ones to go down without a fight. Despite finding difficulty in the Six Nations, Scotland often perform well in the World Cup."
},
{ 		
	"id" : "JPN",
	"name" : "Japan",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "A",
	"rank" : 10,
	"oddsfra" : "150/1",
	"oddsdec" : 150,
	"rwcwins" : 0,
	"description" : "After famously defeating the Spingboks in the the biggest upset of RWC history at RWC2015, the hosts are tipped to do well again this year, cheered on by home support."
},
{ 		
	"id" : "FIJ",
	"name" : "Fiji",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "D",
	"rank" : 11,
	"oddsfra" : "500/1",
	"oddsdec" : 500,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "GRG",
	"name" : "Georgia",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "D",
	"rank" : 12,
	"oddsfra" : "1000/1",
	"oddsdec" : 1000,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "ITA",
	"name" : "Italy",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "B",
	"rank" : 13,
	"oddsfra" : "1000/1",
	"oddsdec" : 1000,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "SAM",
	"name" : "Samoa",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "A",
	"rank" : 14,
	"oddsfra" : "1000/1",
	"oddsdec" : 1000,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "TON",
	"name" : "Tonga",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "C",
	"rank" : 15,
	"oddsfra" : "1000/1",
	"oddsdec" : 1000,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "USA",
	"name" : "USA",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "C",
	"rank" : 16,
	"oddsfra" : "2000/1",
	"oddsdec" : 2000,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "CAN",
	"name" : "Canada",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "B",
	"rank" : 17,
	"oddsfra" : "2500/1",
	"oddsdec" : 2500,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "RUS",
	"name" : "Russia",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "A",
	"rank" : 18,
	"oddsfra" : "2500/1",
	"oddsdec" : 2500,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "URU",
	"name" : "Uruguay",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "D",
	"rank" : 19,
	"oddsfra" : "2500/1",
	"oddsdec" : 2500,
	"rwcwins" : 0,
	"description" : " "
},
{ 		
	"id" : "NAM",
	"name" : "Namibia",
	"multiplier1" : 50,
	"multiplier2" : 45,
	"multiplier3" : 40,
	"multiplier4" : 35,
	"multiplier5" : 30,
	"multiplier6" : 25,
	"multiplier7" : 20,
	"multiplier8" : 15,
	"multiplier20" : 0,
	"group": "B",
	"rank" : 20,
	"oddsfra" : "5000/1",
	"oddsdec" : 5000,
	"rwcwins" : 0,
	"description" : " "
}
];